import "./globals.scss";
import type { Metadata } from "next";
import React from "react";
import { fira_code } from "@/utils";

export const metadata: Metadata = {
	title: "AtsumiFlex | Portfolio",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={fira_code.className}>{children}</body>
		</html>
	);
}
